//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud.Repositories.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers_Storages
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int StorageId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
