//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud.Repositories.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public Storage()
        {
            this.AspNetUsers_Storages = new HashSet<AspNetUsers_Storages>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ClassName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<AspNetUsers_Storages> AspNetUsers_Storages { get; set; }
    }
}
