//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud.Repositories.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFileType
    {
        public int FileTypeId { get; set; }
        public string Name { get; set; }
        public string Extension { get; set; }
        public string IconUrl { get; set; }
    }
}
