//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud.Repositories.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFile
    {
        public UserFile()
        {
            this.FileServers = new HashSet<FileServer>();
        }
    
        public int FileId { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Path { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<FileServer> FileServers { get; set; }
    }
}
