//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud.Storages.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFolder
    {
        public UserFolder()
        {
            this.UserFolders1 = new HashSet<UserFolder>();
        }
    
        public int Id { get; set; }
        public int ParentId { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<UserFolder> UserFolders1 { get; set; }
        public virtual UserFolder UserFolder1 { get; set; }
    }
}
