//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud.Storages.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFile
    {
        public string UserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Path { get; set; }
        public bool IsEditable { get; set; }
        public long Size { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
        public System.DateTime AddedDateTime { get; set; }
        public int DownloadedTimes { get; set; }
        public string Id { get; set; }
        public string FolderId { get; set; }
    }
}
