//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud.Storages.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppSettingKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppSettingKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cloud.Storages.Resources.AppSettingKeys", typeof(AppSettingKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveApplicationUserAgent.
        /// </summary>
        public static string DriveApplicationUserAgent {
            get {
                return ResourceManager.GetString("DriveApplicationUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveClientId.
        /// </summary>
        public static string DriveClientId {
            get {
                return ResourceManager.GetString("DriveClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveClientSecret.
        /// </summary>
        public static string DriveClientSecret {
            get {
                return ResourceManager.GetString("DriveClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveUserCredentalsFolder.
        /// </summary>
        public static string DriveUserCredentalsFolder {
            get {
                return ResourceManager.GetString("DriveUserCredentalsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropboxAccessToken.
        /// </summary>
        public static string DropboxAccessToken {
            get {
                return ResourceManager.GetString("DropboxAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropboxAppKey.
        /// </summary>
        public static string DropboxAppKey {
            get {
                return ResourceManager.GetString("DropboxAppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropboxAppName.
        /// </summary>
        public static string DropboxAppName {
            get {
                return ResourceManager.GetString("DropboxAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropboxAppSecret.
        /// </summary>
        public static string DropboxAppSecret {
            get {
                return ResourceManager.GetString("DropboxAppSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropboxRedirectUri.
        /// </summary>
        public static string DropboxRedirectUri {
            get {
                return ResourceManager.GetString("DropboxRedirectUri", resourceCulture);
            }
        }
    }
}
